version: "3.3"
services:
  backend:
    container_name: nft-publisher-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - redis-network
      - database-network
    depends_on:
      - database
      - redis
    volumes:
      - ./uploads:/app/uploads  
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      BACKEND_PORT: ${BACKEND_PORT}
      BASE_IMAGE_URL: ${BASE_IMAGE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      IPFS_ENDPOINT: ${IPFS_ENDPOINT}
      IPFS_TOKEN: ${IPFS_TOKEN}
      CONTRACT_ROOT_NFT: ${CONTRACT_ROOT_NFT}
      CONTRACT_MARKET_NFT: ${CONTRACT_MARKET_NFT}
      NEAR_NETWORK_ID: ${NEAR_NETWORK_ID}
      NEAR_NODE_URL: ${NEAR_NODE_URL}
      NEAR_WALLET_URL: ${NEAR_WALLET_URL}
      NEAR_HELPER_URL: ${NEAR_HELPER_URL}
      LIKELY_NFTS_ENDPOINT: ${LIKELY_NFTS_ENDPOINT}

  lake:
    container_name: near-lake-microservice-prod
    restart: always
    build:
      context: ./near-lake-microservice
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - redis-network
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
      NEAR_NODE_URL: ${NEAR_NODE_URL}

  database:
    container_name: nft-publisher-database-prod
    image: postgres:alpine
    networks:
      - database-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT}  
    expose:
    - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    container_name: redis-for-microservices-prod
    restart: always
    image: "redis:6.2-alpine"
    command: --port ${REDIS_PORT}
    networks:
      - redis-network
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"

networks:
  redis-network:
  database-network:
