version: '3.3'

services:
  backend:
    container_name: birth-certs-backend
    build:
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - overlay
    # depends_on:
    #   - database
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      BACKEND_PORT: ${BACKEND_PORT}

#   database:
#     container_name: nft-publisher-database
#     image: postgis/postgis:15-3.3
#     networks:
#       - overlay
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     # ports:
#     #   - '${DATABASE_PORT}:5432'
#     restart: always
#     environment:
#       POSTGRES_DB: ${DATABASE_NAME}
#       POSTGRES_USER: ${DATABASE_USERNAME}
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

# networks:
#   overlay:
